version: "2"
services:
  pdns:
    build: . 
    #image: secns/pdns
    links:
    - "db:db"
    ports:
    - "53:53"
    - "53:53/udp"
    - "8080:80"
    - "8081:8081"
    environment:
    - PDNSCONF_API_KEY=DJADcxuG4MaEtf200svqDpBPSraKtwRI
    - PDNSCONF_MASTER=yes
    - PDNSCONF_DEFAULT_SOA_NAME=dnsserver.domain.com
    - PDNSCONF_DNSUPDATE=yes
    - DB_ENV_MYSQL_PASSWORD=DGGdr68SMcjYFdQkuCC2
  db:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=aPYsB84zdNZNmn64sjy
    - MYSQL_DATABASE=pdns
    - MYSQL_USER=pdns
    - MYSQL_PASSWORD=DGGdr68SMcjYFdQkuCC2
